# Generated by Django 3.2.6 on 2021-09-07 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_lastName', models.CharField(max_length=50)),
                ('owner_phoneN', models.CharField(max_length=10)),
                ('owner_email', models.EmailField(max_length=100)),
                ('owner_revenue', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=50)),
                ('tenant_lastName', models.CharField(max_length=50)),
                ('tenant_phoneN', models.CharField(max_length=10)),
                ('tenant_mail', models.CharField(max_length=100)),
                ('tenant_revenue', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_value', models.IntegerField(max_length=20)),
                ('asset_city', models.CharField(max_length=20)),
                ('asset_startDate', models.DateTimeField(default=datetime.datetime(2021, 9, 7, 14, 57, 5, 949144), verbose_name='date published')),
                ('asset_endDate', models.DateTimeField(default=datetime.datetime(2021, 9, 7, 14, 57, 5, 949144), verbose_name='date published')),
                ('asset_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.owner', verbose_name='Owner')),
                ('asset_tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tenant', verbose_name='Tenant')),
            ],
        ),
    ]
