# Generated by Django 3.2.6 on 2021-09-07 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210907_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_adress',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 15, 3, 31, 835169), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 15, 3, 31, 835169), verbose_name='date published'),
        ),
    ]
